[package]
name = "pinit-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
indexmap = "2.12.1"
rust-yaml = "0.0.5"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
